In [1]:
import numpy as np
import scipy as sc
import scipy.linalg
import networkx as nx
import matplotlib.pyplot as plt

In [2]:
# make a matrix
# transform it to tp matrix
# apply power iteration

In [3]:
def print_matrix(mat):
    rows=len(mat)
    columns=len(mat[0])
    for i in range(rows):
        for j in range(columns):
            print(mat[i][j],end=' ')
        print()

In [4]:
def generate_tp_matrix(alpha,G):
    rows=len(G)
    N=rows
    columns=len(G[0])
    P = np.zeros((rows,columns))
    sum_of_1s=[]
    
    #sum_of_1s[rows]
    for i in range(rows):
        rowsum=0;
        for j in range(columns):
            if(G[i][j]==1): rowsum+=1
        sum_of_1s.append(rowsum)
        #print(sum_of_1s[i])
        
    #dividing by row sum
    for i in range(rows):
        for j in range(columns):
            if(G[i][j]==1): 
                temp=G[i][j]/sum_of_1s[i]
                #print(temp)
                P[i][j]=temp
    
    #multiply by 1-alpha
    for i in range(rows):
        for j in range(columns):
            P[i][j]*=(1-alpha)
            
    #adding alpha by n to P
    for i in range(rows):
        for j in range(columns):
            P[i][j]+=(alpha/N)
    return P

In [5]:
G = np.array([[0, 1, 1],
              [1, 0, 0],
              [1, 0, 0]],dtype=float)

In [6]:
P=generate_tp_matrix(0.1,G)
print(G)
print()
print(P)

[[0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]

[[0.03333333 0.48333333 0.48333333]
 [0.93333333 0.03333333 0.03333333]
 [0.93333333 0.03333333 0.03333333]]


In [79]:
test= np.array([[0,0,1,0,0,0,0],
                [0,1,1,0,0,0,0],
                [1,0,1,1,0,0,0],
                [0,0,0,1,1,0,0],
                [0,0,0,0,0,0,1],
                [0,0,0,0,0,1,1],
                [0,0,0,1,1,0,1]], dtype=float)
print(test)

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1. 0. 1.]]


In [8]:
P=generate_tp_matrix(0.14,test)

print(P)

[[0.02       0.02       0.88       0.02       0.02       0.02
  0.02      ]
 [0.02       0.45       0.45       0.02       0.02       0.02
  0.02      ]
 [0.30666667 0.02       0.30666667 0.30666667 0.02       0.02
  0.02      ]
 [0.02       0.02       0.02       0.45       0.45       0.02
  0.02      ]
 [0.02       0.02       0.02       0.02       0.02       0.02
  0.88      ]
 [0.02       0.02       0.02       0.02       0.02       0.45
  0.45      ]
 [0.02       0.02       0.02       0.30666667 0.30666667 0.02
  0.30666667]]


In [9]:
columns=len(P[0])
x=np.zeros(columns)
x[0]=1

print(x)

xp=np.dot(x,P)

xp

[1. 0. 0. 0. 0. 0. 0.]


array([0.02, 0.02, 0.88, 0.02, 0.02, 0.02, 0.02])

In [10]:
def power_itr100(xp,P):
    count=100
    prev=np.zeros(columns)

    while(count):
        prev=xp
        xp=np.dot(xp,P)
        count-=1
    print(xp)

In [11]:
def power_itr_inf(xp,P):
    count=0
    prev=np.zeros(columns)

    while(True):
        if np.array_equal(prev,xp):
            break;
        prev=xp
        xp=np.dot(xp,P)
        count+=1
    print(count)

In [12]:
xp

array([0.02, 0.02, 0.88, 0.02, 0.02, 0.02, 0.02])

In [13]:
power_itr_inf(xp,P)
power_itr100(xp,P)

93
[0.05211042 0.03508772 0.11201311 0.24561199 0.21350156 0.03508772
 0.30658747]


In [14]:
#def input_adj_mat():
irows=int(input("Enter number of points: "))
icolumns=irows
mat=np.zeros((irows,icolumns))
for i in range(irows):
    for j in range(icolumns):
        mat[i][j]=int(input("Is "+str(i)+" and "+str(j)+" connected?\n Press 1 for yes and 0 for NO"))

Enter number of points: 3
Is 0 and 0 connected?
 Press 1 for yes and 0 for NO1
Is 0 and 1 connected?
 Press 1 for yes and 0 for NO1
Is 0 and 2 connected?
 Press 1 for yes and 0 for NO1
Is 1 and 0 connected?
 Press 1 for yes and 0 for NO0
Is 1 and 1 connected?
 Press 1 for yes and 0 for NO1
Is 1 and 2 connected?
 Press 1 for yes and 0 for NO1
Is 2 and 0 connected?
 Press 1 for yes and 0 for NO0
Is 2 and 1 connected?
 Press 1 for yes and 0 for NO0
Is 2 and 2 connected?
 Press 1 for yes and 0 for NO1


In [64]:
mat=np.array([[0,0,1,0,0,0,0],
                [0,1,1,0,0,0,0],
                [1,0,1,1,0,0,0],
                [0,0,0,1,1,0,0],
                [0,0,0,0,0,0,1],
                [0,0,0,0,0,1,1],
                [0,0,0,1,1,0,1]], dtype=float)

In [65]:
P=generate_tp_matrix(0.1,mat)

print(P)

[[0.01428571 0.01428571 0.91428571 0.01428571 0.01428571 0.01428571
  0.01428571]
 [0.01428571 0.46428571 0.46428571 0.01428571 0.01428571 0.01428571
  0.01428571]
 [0.31428571 0.01428571 0.31428571 0.31428571 0.01428571 0.01428571
  0.01428571]
 [0.01428571 0.01428571 0.01428571 0.46428571 0.46428571 0.01428571
  0.01428571]
 [0.01428571 0.01428571 0.01428571 0.01428571 0.01428571 0.01428571
  0.91428571]
 [0.01428571 0.01428571 0.01428571 0.01428571 0.01428571 0.46428571
  0.46428571]
 [0.01428571 0.01428571 0.01428571 0.31428571 0.31428571 0.01428571
  0.31428571]]


In [66]:
columns=len(P[0])
x=np.zeros(columns)
x[0]=1

print(x)

xp=x@P

xp

[1. 0. 0. 0. 0. 0. 0.]


array([0.01428571, 0.01428571, 0.91428571, 0.01428571, 0.01428571,
       0.01428571, 0.01428571])

In [67]:
count=0
prev=np.zeros(columns)

while(count<100):
    prev=xp
    xp=xp@P
    count+=1

In [68]:
xp

array([0.04137723, 0.02597403, 0.09030504, 0.25601355, 0.22892204,
       0.02597403, 0.33143409])

In [36]:
G=nx.from_numpy_matrix(mat)
nx.pagerank(G,0.1)

{0: 0.3333333333333333, 1: 0.3333333333333333, 2: 0.3333333333333333}

In [56]:
mat=np.array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [57]:
Y=generate_tp_matrix(0.1,mat)

In [58]:
tempG=nx.from_numpy_matrix(mat)


In [59]:
nx.pagerank(tempG,0.1)

{0: 0.3333333333333333, 1: 0.3333333333333333, 2: 0.3333333333333333}

In [60]:
columns=len(Y[0])
l=np.zeros(columns)
l[0]=1

print(l)

xp1=l@Y

xp1

[1. 0. 0.]


array([0.33333333, 0.33333333, 0.33333333])

In [61]:
count=0
prev=np.zeros(columns)

while(count<100):
    prev=xp1
    xp1=xp1@Y
    count+=1

In [62]:
xp1

array([0.04761905, 0.08658009, 0.86580087])