In [33]:
import numpy as np
import scipy as sc
import scipy.linalg
import networkx as nx
import matplotlib.pyplot as plt

In [34]:
# make a matrix
# transform it to tp matrix
# apply power iteration

In [35]:
def generate_matrix(n) :
    c = np.full([n,n], np.arange(n))
    c = (abs(np.random.standard_cauchy([n,n])/2) > (np.abs(c - c.T) + 1)) + 0
    c = (c+1e-10) / np.sum((c+1e-10), axis=0)
    return c

In [36]:
def print_matrix(mat):
    rows=len(mat)
    columns=len(mat[0])
    for i in range(rows):
        for j in range(columns):
            print(mat[i][j],end=' ')
        print()

In [37]:
def generate_tp_matrix(alpha,G):
    rows=len(G)
    N=rows
    columns=len(G[0])
    P = np.zeros((rows,columns))
    sum_of_1s=[]
    
    #sum_of_1s[rows]
    for i in range(rows):
        rowsum=0;
        for j in range(columns):
            if(G[i][j]==1): rowsum+=1
        sum_of_1s.append(rowsum)
        #print(sum_of_1s[i])
        
    #dividing by row sum
    for i in range(rows):
        for j in range(columns):
            if(G[i][j]==1): 
                temp=G[i][j]/sum_of_1s[i]
                #print(temp)
                P[i][j]=temp
    
    #multiply by 1-alpha
    for i in range(rows):
        for j in range(columns):
            P[i][j]*=(1-alpha)
            
    #adding alpha by n to P
    for i in range(rows):
        for j in range(columns):
            P[i][j]+=(alpha/N)
    return P

In [38]:
G = np.array([[0, 1, 1],
              [1, 0, 0],
              [1, 0, 0]],dtype=float)

In [40]:
P=generate_tp_matrix(0.1,G)
print(G)
print()
print(P)

[[0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]

[[0.03333333 0.48333333 0.48333333]
 [0.93333333 0.03333333 0.03333333]
 [0.93333333 0.03333333 0.03333333]]


In [64]:
test= np.array([[0,0,1,0,0,0,0],
                [0,1,1,0,0,0,0],
                [1,0,1,1,0,0,0],
                [0,0,0,1,1,0,0],
                [0,0,0,0,0,0,1],
                [0,0,0,0,0,1,1],
                [0,0,0,1,1,0,1]], dtype=float)


In [71]:
P=generate_tp_matrix(0.14,test)

print(P)

[[0.02       0.02       0.88       0.02       0.02       0.02
  0.02      ]
 [0.02       0.45       0.45       0.02       0.02       0.02
  0.02      ]
 [0.30666667 0.02       0.30666667 0.30666667 0.02       0.02
  0.02      ]
 [0.02       0.02       0.02       0.45       0.45       0.02
  0.02      ]
 [0.02       0.02       0.02       0.02       0.02       0.02
  0.88      ]
 [0.02       0.02       0.02       0.02       0.02       0.45
  0.45      ]
 [0.02       0.02       0.02       0.30666667 0.30666667 0.02
  0.30666667]]


In [72]:
columns=len(M[0])
x=np.zeros(columns)
x[0]=1

print(x)

xp=np.dot(x,M)

xp

[1. 0. 0. 0. 0. 0. 0.]


array([0.02, 0.02, 0.88, 0.02, 0.02, 0.02, 0.02])

In [78]:
def power_itr100(xp,P):
    count=100
    prev=np.zeros(columns)

    while(count):
        prev=xp
        xp=np.dot(xp,P)
        count-=1
    print(xp)

In [79]:
def power_itr_inf(xp,P):
    count=0
    prev=np.zeros(columns)

    while(True):
        if np.array_equal(prev,xp):
            break;
        prev=xp
        xp=np.dot(xp,P)
        count+=1
    print(count)

In [80]:
xp

array([0.02, 0.02, 0.88, 0.02, 0.02, 0.02, 0.02])

In [81]:
power_itr_inf(xp,P)
power_itr100(xp,P)

93
[0.05211042 0.03508772 0.11201311 0.24561199 0.21350156 0.03508772
 0.30658747]


In [26]:
#def input_adj_mat():
irows=int(input("Enter number of points: "))
icolumns=irows
mat=np.zeros((irows,icolumns))
for i in range(irows):
    for j in range(icolumns):
        mat[i][j]=int(input("Is "+str(i)+" and "+str(j)+" connected?\n Press 1 for yes and 0 for NO"))

Enter number of points: 3
Is 0 and 0 connected?
 Press 1 for yes and 0 for NO1
Is 0 and 1 connected?
 Press 1 for yes and 0 for NO0
Is 0 and 2 connected?
 Press 1 for yes and 0 for NO0
Is 1 and 0 connected?
 Press 1 for yes and 0 for NO0
Is 1 and 1 connected?
 Press 1 for yes and 0 for NO1
Is 1 and 2 connected?
 Press 1 for yes and 0 for NO0
Is 2 and 0 connected?
 Press 1 for yes and 0 for NO0
Is 2 and 1 connected?
 Press 1 for yes and 0 for NO0
Is 2 and 2 connected?
 Press 1 for yes and 0 for NO1


In [27]:
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
M=generate_tp_matrix(0.14,mat)

print(M)

[[0.90666667 0.04666667 0.04666667]
 [0.04666667 0.90666667 0.04666667]
 [0.04666667 0.04666667 0.90666667]]


In [29]:
columns=len(M[0])
x=np.zeros(columns)
x[0]=1

print(x)

xp=np.dot(x,M)

xp

[1. 0. 0.]


array([0.90666667, 0.04666667, 0.04666667])

In [30]:
count=0
prev=np.zeros(columns)

while(True):
    if np.array_equal(prev,xp):
        break
    prev=xp
    xp=np.dot(xp,M)
    count+=1

In [31]:
xp

array([0.33333333, 0.33333333, 0.33333333])